### ISSUE TITLE
Many many errors when set to below 360 degree vision

### ISSUE THREAD

**Issue by BlackMoons** [manuelVo/foundryvtt-lichtgeschwindigkeit#24]
Hi. I recently tried fiddling with limited view sight, and got massive errors whenever trying to move the characters or click various GUI elements whenever a token with vision was set to "140 Sight Angle" "0 Dim Vision" and "0 Bright Vision"

Setting it to 1 dim vision or 360 degree sight angle seems to eliminate the errors.

Error oddly does not occur if 'perfect vision' is enabled, so make sure to not be using that module.

**Comment by BlackMoons** [comment]
Here is the error it left:
`
panicked at 'assertion failed: `(left != right)`
  left: `Point { x: 2590.89734721, y: 2029.551326395 }`,
 right: `Point { x: 2590.89734721, y: 2029.551326395 }`', src/geometry.rs:202:13

Stack:

Error
    at imports.wbg.__wbg_new_59cb74e423758ede (http://127.0.0.1:30000/modules/lichtgeschwindigkeit/wasm/lichtgeschwindigkeit.js:774:19)
    at http://127.0.0.1:30000/modules/lichtgeschwindigkeit/wasm/lichtgeschwindigkeit_bg.wasm:wasm-function[96]:0x240bf
    at http://127.0.0.1:30000/modules/lichtgeschwindigkeit/wasm/lichtgeschwindigkeit_bg.wasm:wasm-function[272]:0x2a0ef
    at http://127.0.0.1:30000/modules/lichtgeschwindigkeit/wasm/lichtgeschwindigkeit_bg.wasm:wasm-function[151]:0x2842b
    at http://127.0.0.1:30000/modules/lichtgeschwindigkeit/wasm/lichtgeschwindigkeit_bg.wasm:wasm-function[159]:0x28990
    at http://127.0.0.1:30000/modules/lichtgeschwindigkeit/wasm/lichtgeschwindigkeit_bg.wasm:wasm-function[211]:0x29a62
    at http://127.0.0.1:30000/modules/lichtgeschwindigkeit/wasm/lichtgeschwindigkeit_bg.wasm:wasm-function[203]:0x298ee
    at http://127.0.0.1:30000/modules/lichtgeschwindigkeit/wasm/lichtgeschwindigkeit_bg.wasm:wasm-function[208]:0x299d8
    at http://127.0.0.1:30000/modules/lichtgeschwindigkeit/wasm/lichtgeschwindigkeit_bg.wasm:wasm-function[114]:0x25e39
    at http://127.0.0.1:30000/modules/lichtgeschwindigkeit/wasm/lichtgeschwindigkeit_bg.wasm:wasm-function[174]:0x2901a
    at http://127.0.0.1:30000/modules/lichtgeschwindigkeit/wasm/lichtgeschwindigkeit_bg.wasm:wasm-function[87]:0x22e1a
    at http://127.0.0.1:30000/modules/lichtgeschwindigkeit/wasm/lichtgeschwindigkeit_bg.wasm:wasm-function[36]:0x955e
    at http://127.0.0.1:30000/modules/lichtgeschwindigkeit/wasm/lichtgeschwindigkeit_bg.wasm:wasm-function[72]:0x201f5
    at Module.computePolygon (http://127.0.0.1:30000/modules/lichtgeschwindigkeit/wasm/lichtgeschwindigkeit.js:212:20)
    at WallsLayer.wasmComputePolygon (http://127.0.0.1:30000/modules/lichtgeschwindigkeit/js/raycasting.js:84:32)
    at PointSource.initialize (http://127.0.0.1:30000/scripts/foundry.js:37475:37)
    at Token5e.updateSource (http://127.0.0.1:30000/scripts/foundry.js:44936:19)
    at Token5e._onUpdate (http://127.0.0.1:30000/scripts/foundry.js:45944:14)
    at TokenDocument5e._onUpdate (http://127.0.0.1:30000/scripts/foundry.js:8511:38)
    at TokenDocument5e._onUpdate (http://127.0.0.1:30000/scripts/foundry.js:16807:18)
    at ClientDatabaseBackend.callback (http://127.0.0.1:30000/scripts/foundry.js:8963:11)
    at http://127.0.0.1:30000/scripts/foundry.js:8946:43
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleUpdateEmbeddedDocuments (http://127.0.0.1:30000/scripts/foundry.js:8946:33)
    at ClientDatabaseBackend._updateEmbeddedDocuments (http://127.0.0.1:30000/scripts/foundry.js:8835:17)
    at async Function.updateDocuments (http://127.0.0.1:30000/common/abstract/document.mjs:366:21)
    at async TokenDocument5e.update (http://127.0.0.1:30000/common/abstract/document.mjs:448:21)
    at async TokenConfig._onSubmit (http://127.0.0.1:30000/scripts/foundry.js:2825:7)


imports.wbg.__wbg_error_4bb6c2a97407129a @ lichtgeschwindigkeit.js:786
$func96 @ lichtgeschwindigkeit_bg.wasm:0x2418b
$func272 @ lichtgeschwindigkeit_bg.wasm:0x2a0ef
$func151 @ lichtgeschwindigkeit_bg.wasm:0x2842b
$func159 @ lichtgeschwindigkeit_bg.wasm:0x28990
$func211 @ lichtgeschwindigkeit_bg.wasm:0x29a62
$func203 @ lichtgeschwindigkeit_bg.wasm:0x298ee
$func208 @ lichtgeschwindigkeit_bg.wasm:0x299d8
$func114 @ lichtgeschwindigkeit_bg.wasm:0x25e39
$func174 @ lichtgeschwindigkeit_bg.wasm:0x2901a
$func87 @ lichtgeschwindigkeit_bg.wasm:0x22e1a
$func36 @ lichtgeschwindigkeit_bg.wasm:0x955e
$computePolygon @ lichtgeschwindigkeit_bg.wasm:0x201f5
computePolygon @ lichtgeschwindigkeit.js:212
wasmComputePolygon @ raycasting.js:84
initialize @ foundry.js:37475
updateSource @ foundry.js:44936
_onUpdate @ foundry.js:45944
_onUpdate @ foundry.js:8511
_onUpdate @ foundry.js:16807
callback @ foundry.js:8963
(anonymous) @ foundry.js:8946
_handleUpdateEmbeddedDocuments @ foundry.js:8946
_updateEmbeddedDocuments @ foundry.js:8835
async function (async)
_updateEmbeddedDocuments @ foundry.js:8824
update @ backend.mjs:153
async function (async)
update @ backend.mjs:151
updateDocuments @ document.mjs:366
update @ document.mjs:448
_updateObject @ foundry.js:30821
_onSubmit @ foundry.js:2825
raycasting.js:87 RuntimeError: unreachable
    at lichtgeschwindigkeit_bg.wasm:0x28447
    at lichtgeschwindigkeit_bg.wasm:0x28990
    at lichtgeschwindigkeit_bg.wasm:0x29a62
    at lichtgeschwindigkeit_bg.wasm:0x298ee
    at lichtgeschwindigkeit_bg.wasm:0x299d8
    at lichtgeschwindigkeit_bg.wasm:0x25e39
    at lichtgeschwindigkeit_bg.wasm:0x2901a
    at lichtgeschwindigkeit_bg.wasm:0x22e1a
    at lichtgeschwindigkeit_bg.wasm:0x955e
    at lichtgeschwindigkeit_bg.wasm:0x201f5
    at Module.computePolygon (lichtgeschwindigkeit.js:212)
    at WallsLayer.wasmComputePolygon (raycasting.js:84)
    at PointSource.initialize (foundry.js:37475)
    at Token5e.updateSource (foundry.js:44936)
    at Token5e._onUpdate (foundry.js:45944)
    at TokenDocument5e._onUpdate (foundry.js:8511)
    at TokenDocument5e._onUpdate (foundry.js:16807)
    at ClientDatabaseBackend.callback (foundry.js:8963)
    at foundry.js:8946
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleUpdateEmbeddedDocuments (foundry.js:8946)
    at ClientDatabaseBackend._updateEmbeddedDocuments (foundry.js:8835)
    at async Function.updateDocuments (document.mjs:366)
    at async TokenDocument5e.update (document.mjs:448)
    at async TokenConfig._onSubmit (foundry.js:2825)
wasmComputePolygon @ raycasting.js:87
initialize @ foundry.js:37475
updateSource @ foundry.js:44936
_onUpdate @ foundry.js:45944
_onUpdate @ foundry.js:8511
_onUpdate @ foundry.js:16807
callback @ foundry.js:8963
(anonymous) @ foundry.js:8946
_handleUpdateEmbeddedDocuments @ foundry.js:8946
_updateEmbeddedDocuments @ foundry.js:8835
async function (async)
_updateEmbeddedDocuments @ foundry.js:8824
update @ backend.mjs:153
async function (async)
update @ backend.mjs:151
updateDocuments @ document.mjs:366
update @ document.mjs:448
_updateObject @ foundry.js:30821
_onSubmit @ foundry.js:2825
raycasting.js:88 Data to reproduce the error (please always include this in bug reports!):
wasmComputePolygon @ raycasting.js:88
initialize @ foundry.js:37475
updateSource @ foundry.js:44936
_onUpdate @ foundry.js:45944
_onUpdate @ foundry.js:8511
_onUpdate @ foundry.js:16807
callback @ foundry.js:8963
(anonymous) @ foundry.js:8946
_handleUpdateEmbeddedDocuments @ foundry.js:8946
_updateEmbeddedDocuments @ foundry.js:8835
async function (async)
_updateEmbeddedDocuments @ foundry.js:8824
update @ backend.mjs:153
async function (async)
update @ backend.mjs:151
updateDocuments @ document.mjs:366
update @ document.mjs:448
_updateObject @ foundry.js:30821
_onSubmit @ foundry.js:2825
raycasting.js:113 <~"*iOZQ9@mY:_\Y&2i!"E@Rh#c/e3IU#f7JW"[rRoJYQSa=Y/!p;.Cc*d+0j`rLecW7gB:<5EX>JK7fXoF7'?[b=t`d?Jb68S9o<P8;o82e0+@,dHu.`5'A]l<%<lV&*!UsIWumN,TfK*NA7D=T?Ymd_bIbM@$%HaY'R@DaY"#VafS+10h1>Zg.348!0^+n<5Z&qHra*YN2>(U'@#TRN+k4rnsV_:h(33*#+4JPJP'F2:<P*r0FHrB)IO7SWAMC9?\U%i1!*]SGIRX:>gNJdW"l<h^p*d?iTaFL:I)[t)D8hhDE=gYWW>R"8#g<S8M93G@!'/XdK$'A^.JK$mVIFY=IO"dXd75f-WRbr9=(OrAk1P:c;s?H!*G]Q<7MhLgn%?5NA2Di=#ITM4'^BU.Le)CM,\C5^uQMB:^o,#a'U<U1!0F$8n1P8K2e<<6Ek[B5Qa]c?WCf($sBg#4!fDcq]44MQEPc(bf%]S*\K<7-f5A<e/N9XmZh:^E8H"7edX;.itke?S4i~>
rustifyParams @ raycasting.js:113
logParams @ raycasting.js:76
wasmComputePolygon @ raycasting.js:89
initialize @ foundry.js:37475
updateSource @ foundry.js:44936
_onUpdate @ foundry.js:45944
_onUpdate @ foundry.js:8511
_onUpdate @ foundry.js:16807
callback @ foundry.js:8963
(anonymous) @ foundry.js:8946
_handleUpdateEmbeddedDocuments @ foundry.js:8946
_updateEmbeddedDocuments @ foundry.js:8835
async function (async)
_updateEmbeddedDocuments @ foundry.js:8824
update @ backend.mjs:153
async function (async)
update @ backend.mjs:151
updateDocuments @ document.mjs:366
update @ document.mjs:448
_updateObject @ foundry.js:30821
_onSubmit @ foundry.js:2825
foundry.js:2828 RuntimeError: unreachable
    at lichtgeschwindigkeit_bg.wasm:0x28447
    at lichtgeschwindigkeit_bg.wasm:0x28990
    at lichtgeschwindigkeit_bg.wasm:0x29a62
    at lichtgeschwindigkeit_bg.wasm:0x298ee
    at lichtgeschwindigkeit_bg.wasm:0x299d8
    at lichtgeschwindigkeit_bg.wasm:0x25e39
    at lichtgeschwindigkeit_bg.wasm:0x2901a
    at lichtgeschwindigkeit_bg.wasm:0x22e1a
    at lichtgeschwindigkeit_bg.wasm:0x955e
    at lichtgeschwindigkeit_bg.wasm:0x201f5
    at Module.computePolygon (lichtgeschwindigkeit.js:212)
    at WallsLayer.wasmComputePolygon (raycasting.js:84)
    at PointSource.initialize (foundry.js:37475)
    at Token5e.updateSource (foundry.js:44936)
    at Token5e._onUpdate (foundry.js:45944)
    at TokenDocument5e._onUpdate (foundry.js:8511)
    at TokenDocument5e._onUpdate (foundry.js:16807)
    at ClientDatabaseBackend.callback (foundry.js:8963)
    at foundry.js:8946
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleUpdateEmbeddedDocuments (foundry.js:8946)
    at ClientDatabaseBackend._updateEmbeddedDocuments (foundry.js:8835)
    at async Function.updateDocuments (document.mjs:366)
    at async TokenDocument5e.update (document.mjs:448)
    at async TokenConfig._onSubmit (foundry.js:2825)
`

**Comment by BlackMoons** [comment]
Thank you very much for the quick fix and release!
